# Generated by Django 2.1.3 on 2018-11-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nich', models.CharField(max_length=16, verbose_name='昵称')),
                ('yhm', models.CharField(max_length=32, verbose_name='用户名')),
                ('mima', models.CharField(max_length=32, verbose_name='密码')),
                ('youx', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('bum', models.IntegerField(choices=[(0, '信息科'), (1, '农水科'), (2, '灌溉科'), (3, '财务科')], default=0, verbose_name='用户部门')),
                ('shouj', models.IntegerField(verbose_name='手机号码')),
                ('toux', models.ImageField(upload_to='', verbose_name='用户头像')),
                ('shij', models.DateTimeField(verbose_name='注册时间')),
            ],
        ),
    ]
