# Generated by Django 2.1.3 on 2018-11-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfapp', '0005_auto_20181127_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aV', models.IntegerField(verbose_name='A项电压')),
                ('bV', models.IntegerField(verbose_name='B项电压')),
                ('cV', models.IntegerField(verbose_name='C项电压')),
                ('aA', models.IntegerField(verbose_name='A项电流')),
                ('bA', models.IntegerField(verbose_name='B项电流')),
                ('cA', models.IntegerField(verbose_name='C项电流')),
                ('pdshij', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
            ],
            options={
                'verbose_name': '配电检测',
                'verbose_name_plural': '配电检测',
            },
        ),
        migrations.CreateModel(
            name='Shebdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shebmc', models.CharField(max_length=32, verbose_name='设备名称')),
                ('anzhwz', models.CharField(max_length=32, verbose_name='安装位置')),
                ('shebIP', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('shebxt', models.IntegerField(choices=[(0, '监控系统'), (1, '森林防火系统'), (2, '网络系统'), (3, '机房系统'), (4, '配电系统'), (5, '智能管理系统')], default=0, verbose_name='子系统')),
                ('yssj', models.DateField(verbose_name='验收时间')),
                ('zbsj', models.DateField(verbose_name='质保到期时间')),
                ('shebtp', models.ImageField(upload_to='static/dist/img/', verbose_name='设备图片')),
            ],
            options={
                'verbose_name': '设备管理',
                'verbose_name_plural': '设备管理',
            },
        ),
        migrations.CreateModel(
            name='Wd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jfwd', models.IntegerField(verbose_name='机房温度')),
                ('zhswd', models.IntegerField(verbose_name='指挥室温度')),
                ('fwqjgwd', models.IntegerField(verbose_name='服务器机柜温度')),
                ('pdjgwd', models.IntegerField(verbose_name='配电机柜温度')),
                ('jkjgwd', models.IntegerField(verbose_name='监控机柜温度')),
                ('ccjgwd', models.IntegerField(verbose_name='存储机柜温度')),
                ('dapzwd', models.IntegerField(verbose_name='大屏左温度')),
                ('dapywd', models.IntegerField(verbose_name='大屏右温度')),
                ('wdshij', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
            ],
            options={
                'verbose_name': '温度检测',
                'verbose_name_plural': '温度检测',
            },
        ),
        migrations.CreateModel(
            name='Yjgl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bjshij', models.DateTimeField(verbose_name='报警时间')),
                ('bjlx', models.IntegerField(choices=[(0, '电压过高'), (1, '电流过高'), (2, '漏水'), (3, '温度过高')], default=0, verbose_name='报警类型')),
                ('bjxx', models.CharField(max_length=64, verbose_name='报警信息')),
            ],
            options={
                'verbose_name': '报警信息',
                'verbose_name_plural': '报警信息',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='user',
            name='shij',
            field=models.DateTimeField(auto_now=True, verbose_name='注册时间'),
        ),
    ]
